#!/bin/bash
git submodule update --init --remote --force
rebuild_venv=$1
rebuild_venv="${rebuild_venv:-0}"
source utility-repo-scripts/setup_python_app.sh \
	--debug \
	--package_manager="pip" \
	--rebuild_venv="$rebuild_venv" \
	--python_version="3.8" \
	--python_formatter="" \
	--pylint_enabled \
	--flake8_enabled \
	--overwrite_vscode_settings \
	--overwrite_vscode_launch \
	--line_length=125
